# --- START OF FILE techniques.py ---

TECHNIQUES_DB = {
    # --- HIROTO AKAGI ---
    "Legend Manifestation Technique": "- CONCEPT: Intercepts and weaponizes mythological archetypes generated by humanity’s collective belief.\n- ACQUISITION: User hunts and binds entities as shikigami.\n- MECHANICS: Stored in a convergence reservoir, summoned with full physical form and abilities.\n- LIMITATION: Destruction during manifestation means permanent loss.",
    "Command Hierarchy": "Hiroto commands bound mythologies via Direct Command (precise), Tactical Command (goal-oriented), or Autonomous Mode (instinct-based).",
    "Technique Synergy": "Combining different mythological entities (e.g., Serpent + Storm deity) to create complex, multi-elemental interactions.",
    "Below-Average Close Quarters Combat": "Hiroto fights as a backline battlefield controller. He is highly vulnerable in direct physical melee, relying purely on evasion and basic cursed energy reinforcement to escape.",
    "Domain Expansion: Mythological Convergence Field": "- CONCEPT: A barrier domain that saturates the area in mythological energy.\n- EFFECT: Hiroto becomes a secondary vessel for active shikigami, allowing him to personally dual-cast their techniques.\n- LIMITATION: Extreme cursed energy drain; risk of technique overload/backlash.",
    "Technique Convergence": "The secondary-vessel effect of his Domain. Duplicates every active technique, forcing the enemy to fight the shikigami AND Hiroto wielding the exact same ability simultaneously.",

    # --- CHOSO & GETO ---
    "Blood Manipulation": "Choso can control the shape, movement, and properties of his own blood, forming projectiles or hardening it for defense.",
    "Flowing Red Scale": "Boosts physical abilities by raising blood pressure and body temperature. Risks thrombosis.",
    "Flowing Red Scale: Stack": "Focuses the boost into a specific body part, such as eyes for reaction speed.",
    "Supernova": "Compresses multiple blood projectiles into a single explosive area-of-effect release.",
    "Blood Meteorite": "A hardened blood projectile fired at high velocity.",
    "Cursed Spirit Manipulation": "Absorbs and stores cursed spirits by ingesting them to deploy in battle.",
    "Uzumaki": "Releases multiple stored spirits simultaneously, combining their energy into a massive blast.",
    "Maximum: Uzumaki": "Amplified Uzumaki using Special Grade stored spirits.",

    # --- GOJO ---
    "Limitless": "Brings the mathematical concept of infinity into reality. Allows absolute control over space at an atomic level.",
    "Infinity": "Neutral Limitless. Creates an invisible spatial distortion that slows down approaching objects infinitely so they never touch the user.",
    "Cursed Technique Lapse: Blue": "Creates a localized vacuum of negative space that forcefully attracts everything toward it like a black hole.",
    "Cursed Technique Reversal: Red": "A highly condensed orb of space powered by positive energy that violently repels everything with explosive force.",
    "Hollow Technique: Purple": "Collides Blue and Red to generate an imaginary mass that erases matter at the atomic level.",
    "Six Eyes": "Rare ocular trait granting extraordinary perception and near-zero cursed energy consumption.",
    "Domain Expansion: Unlimited Void": "Forces the target's mind into the center of the Limitless, flooding their brain with endless raw information, causing instant catatonia.",

    # --- YUJI ---
    "Superhuman Physicals": "Abnormally dense muscle mass. Can shatter concrete and run at superhuman speeds without cursed energy.",
    "Divergent Fist": "A martial arts technique where the physical strike hits first, followed by a secondary impact of lagging cursed energy.",
    "Black Flash": "A spatial distortion phenomenon amplifying strike power. Yuji has an unparalleled instinct for it.",
    "Shrine": "Sukuna's inherited technique. Manifests as physical invisible slashes.",
    "Soul Strike": "Physical attacks that strike the barrier between souls directly, bypassing physical durability.",

    # --- MEGUMI ---
    "Ten Shadows Technique": "Uses shadows to summon up to ten shikigami. Requires defeating them in a taming ritual first.",
    "Divine Dogs": "Twin wolf shikigami that track curses and devour them.",
    "Nue": "An owl-like shikigami that flies and strikes with electrical shocks.",
    "Rabbit Escape": "Summons a massive swarm of rabbits to act as a smokescreen.",
    "Shadow Manipulation": "Physically hides inside shadows, stores weapons, and traps enemies in shadow pools.",
    "Domain Expansion: Chimera Shadow Garden": "An incomplete domain flooding the area with fluid shadow, allowing infinite shikigami summons and physical clones.",
    "Eight-Handled Sword Divergent Sila Divine General Mahoraga": "The strongest shikigami. Adapts to any and all phenomena after taking a hit.",

    # --- SUKUNA ---
    "Dismantle": "A standard, invisible flying slash used to dismantle objects and weaker sorcerers.",
    "Cleave": "A slash used by physical touch that automatically adjusts its power based on target toughness.",
    "Furnace (Divine Flame)": "Generates a potent arrow of pure fire causing a devastating thermobaric explosion.",
    "Reverse Cursed Technique": "Near-instantaneous and flawless healing. Can regenerate severed limbs.",
    "Domain Expansion: Malevolent Shrine": "A barrier-less domain that relentlessly bombards a 200-meter radius with Cleave and Dismantle.",
    "World-Cutting Slash": "Reality-breaking slash targeting the fabric of space, completely bypassing physical durability and Infinity.",

    # --- YUTA ---
    "Rika": "External cursed energy storage and weapon vault. Grants near-infinite energy for 5 minutes.",
    "Copy": "Unconditionally copies innate techniques of other sorcerers while connected to Rika.",
    "Immense Cursed Energy": "Reserves vastly exceeding Gojo's, making him incredibly durable.",
    "Reverse Cursed Technique Output": "Capable of outputting positive energy to heal OTHER people.",
    "Domain Expansion: Authentic Mutual Love": "Traps opponents in a battlefield of katanas, each containing a copied technique for instant use.",

    # --- MAKI ---
    "Heavenly Restriction (Incomplete)": "Traded cursed energy for superhuman strength. Requires glasses to see curses.",
    "Master Weapons Specialist": "The most proficient weapon user at Jujutsu High.",
    "Heavenly Restriction (Complete)": "0 Cursed Energy. God-like physical abilities, healing factor, and soul perception.",
    "Domain Immunity": "Because she has exactly zero cursed energy, domain barriers treat her as an 'inanimate object', making her immune to guaranteed hits."
}